### ISSUE TITLE
v0.3.0 failing: Invalid `Dangerfile` file: (./.swiftlint.yml)

### ISSUE THREAD

**Issue by sam-w** [ashfurrow/danger-swiftlint#26]
I'm getting errors when using danger-swiftlint both locally (osx) and on Circle CI (also osx), since upgrading to 0.3.0. `swiftlint` works fine run by itself, and downgrading back to 0.2.1 fixes the problem.

Output from `bundle exec danger local`:

```
Running your Dangerfile against this PR - https://github.com/XXX/XXX/pull/129
Turning on --verbose

Info:
... (removed to keep this short, let me know if it might be relevant)

[!] The exception involves the following plugins:
 -  danger-swiftlint

bundler: failed to load command: danger (/usr/local/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: (./.swiftlint.yml): did not find expected key while parsing a block mapping at line 3 column 1
 #  from Dangerfile:2
 #  -------------------------------------------
 #  swiftlint.config_file = "./.swiftlint.yml"
 >  swiftlint.lint_files
 #  
 #  -------------------------------------------

  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:377:in `parse'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:325:in `parse'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:252:in `load'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:471:in `block in load_file'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:471:in `open'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/psych.rb:471:in `load_file'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-swiftlint-0.3.0/lib/danger_plugin.rb:48:in `block in lint_files'
  /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/tempfile.rb:295:in `open'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-swiftlint-0.3.0/lib/danger_plugin.rb:43:in `lint_files'
  Dangerfile:2:in `block in parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/lib/danger/commands/local.rb:109:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.1.1/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:22:in `load'
  /usr/local/bin/danger:22:in `<top (required)>'
```

`.swiftlint.yml`:

```
# custom linter rules defined and tested at https://github.com/XXX/XXX

excluded:
  - Carthage
  - Pods

line_length:
  - 210
  - 220

type_name:
  min_length: 2
  max_length:
    - 60
    - 80

variable_name:
  min_length: 1
  max_length:
    - 60
    - 80

large_tuple:
  - 4

function_parameter_count:
  - 6

disabled_rules:
  - trailing_whitespace #this should stay disabled
  - todo #should stay disabled
  - nesting #should stay disabled
  - opening_brace #keep disabled, but enabled and run autocorrect every now and then
  - closing_brace #keep disabled, but enabled and run autocorrect every now and then
  - force_try
  - force_cast
  - type_body_length
  - function_body_length
  - file_length
  - vertical_parameter_alignment
  - redundant_optional_initialization
  - redundant_string_enum_value
  - trailing_newline #for now
  - vertical_whitespace #for now
  - line_length #for now
  - comma #for now
  - trailing_comma #for now
  - colon #for now
  - operator_whitespace #for now
  - nimble_operator #for now
  - statement_position #for now
  - variable_name #for now
  - implicit_getter #for now
  - syntactic_sugar #for now
  - control_statement #for now
  - unused_closure_parameter #for now
  - mark #for now
  - weak_delegate #for now
  - cyclomatic_complexity #for now
  - explicit_init #for now
  - overridden_super_call #for now

 opt_in_rules:
  - overridden_super_call
  - redundant_nil_coalesing
  - explicit_init
  - nimble_operator

custom_rules:
  localized_string:
    name: "Localized String Dynamic Key"
    regex: 'NSLocalizedString'
    message: "User facing strings don't belong in the network SDK!"
    severity: error
  nscoding:
    name: "NSCoding"
    regex: '(\bNSCoding\b|\bNSCoder\b|\bNSSecureCoding\b|\bclassForCoder\b|\bsupportsSecureCoding\b)'
    message: "Don\'t use NSCoding\/NSSecureCoding"
    severity: error
#  nested_guard:
#    name: "Nested Guard"
#    regex: '(?:\bif\b|\bswitch\b|\bfor\b)[^\{\n:]*\{[^\}]*[^\}]*^\s*(guard).*$'
#    message: "guard may not be nested inside other control flow statements (see Domain SE-0010)"
#    severity: warning
  unique_error_domain:
    name: "Unique Error Domain"
    regex: 'DomainExceptionLogging\.(?:\w+WithMessage\(|.*domain: )(?:(\"[^\"\n]*\\\([^\)\n]+\)[^\"\n]*\")|([^\"\n]+)[\,\)])'
    message: "Error domains should be general and non-unique, to facilitate error grouping"
    severity: warning
```
